### ISSUE TITLE
Error while adding to Home Assistant

### ISSUE THREAD

**Issue by cbergmann** [liudger/python-bsblan#783]
**Describe the bug**
hi, I try to add a bsblan device to home assistant. I can reach the bsblan webinterface and read configuration values.

**To Reproduce**
When I add the Integration to home assistant with the correct hostname (IP-Adress) and username-password combination it fails to initialize the integration.

The Log shows the following lines:
```
2023-10-27 06:11:59.259 ERROR (MainThread) [homeassistant.components.bsblan] Unexpected error fetching bsblan_192.168.2.187 data: zip() argument 2 is shorter than argument 1
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/homeassistant/components/bsblan/coordinator.py", line 51, in _async_update_data
    return await self.client.state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/homeassistant/lib/python3.11/site-packages/bsblan/bsblan.py", line 171, in state
    data = dict(zip(self._heating_params, list(data.values()), strict=True))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zip() argument 2 is shorter than argument 1
```

**Expected behavior**
I would suspect that entities are created.

**Additional context**
I use Home Assitant Core on a raspberry pi 3. 
Here are the installed versions of homeassistant and python-bsblan:
```
(homeassistant) homeassistant@homepi /srv/homeassistant $ pip show homeassistant python-bsblan
Name: homeassistant
Version: 2023.10.4
Summary: Open-source home automation platform running on Python 3.
Home-page:
Author:
Author-email: The Home Assistant Authors <hello@home-assistant.io>
License: Apache-2.0
Location: /srv/homeassistant/lib/python3.11/site-packages
Requires: aiohttp, astral, atomicwrites-homeassistant, attrs, awesomeversion, bcrypt, certifi, ciso8601, cryptography, home-assistant-bluetooth, httpx, ifaddr, Jinja2, lru-dict, orjson, packaging, pip, PyJWT, pyOpenSSL, python-slugify, PyYAML, requests, typing-extensions, ulid-transform, voluptuous, voluptuous-serialize, yarl
Required-by:
---
Name: python-bsblan
Version: 0.5.16
Summary: Asynchronous Python client for BSBLAN
Home-page: https://github.com/liudger/python-bsblan
Author: Willem-Jan van Rootselaar
Author-email: liudgervr@gmail.com
License: MIT
Location: /srv/homeassistant/lib/python3.11/site-packages
Requires: aiohttp, backoff, packaging, pydantic, yarl
Required-by:
```

**Comment by liudger** [comment]
which version of bsblan is on the board?

**Comment by FlorianLaunay** [comment]
Hello @liudger, I am also concerned by this issue. I am using version `3.2.2-20230606224119` with for now a rudimentary set of parameters. Which version of BSB-LAN do you support ?

**Comment by DavidS** [comment]
I had the same issue but could fix it by reading the /Q function ("Reglerspezifische Parameterliste") docs and then using the BSB_LAN_custom_defs.h from 2.2.1.

(I've also done the rest of the recommended actions there). Now the home assistant device configured correctly and I have a thermostat device :-D

**Comment by DavidS** [comment]
PS: with the "proper" custom_defs.h from the bsb lan folks, the error re-appeared

**Comment by DavidS** [comment]
Could it be that the library gets confused because the API_V3 constants use `700.0`, but the API doesn't return such values?

![2023-11-11_19MS+0100_502x491](https://github.com/liudger/python-bsblan/assets/27712/8a186f95-0928-4c67-929b-22ab97cc9315)

**Comment by DavidS** [comment]
Here's the difference between the working and failing situation:

# working

```
BSBLAN heating_params: ['hvac_mode', 'target_temperature', 'hvac_mode2', 'hvac_action', 'current_temperature', 'room1_thermostat_mode']
BSBLAN data: {
    '700': {'name': 'Betriebsart', 'dataType_name': 'ENUM', 'dataType_family': 'ENUM', 'destination': '0', 'error': 0, 'value': '1', 'desc': 'Automatik', 'dataType': 1, 'readonly': 0, 'readwrite': 0, 'unit': ''}, 
    '710': {'name': 'Komfortsollwert', 'dataType_name': 'TEMP', 'dataType_family': 'VALS', 'destination': '0', 'error': 0, 'value': '23.0', 'desc': '', 'precision': 0.1, 'dataType': 0, 'readonly': 0, 'readwrite': 0, 'unit': '°C'}, 
    '900': {'name': 'Betriebsart', 'dataType_name': 'ENUM', 'dataType_family': 'ENUM', 'destination': '0', 'error': 0, 'value': '1', 'desc': 'Schutzbetrieb', 'dataType': 1, 'readonly': 0, 'readwrite': 0, 'unit': ''}, 
    '8000': {'name': 'Status Heizkreis 1', 'dataType_name': 'ENUM', 'dataType_family': 'ENUM', 'destination': '0', 'error': 0, 'value': '114', 'desc': 'Heizbetrieb Komfort', 'dataType': 1, 'readonly': 1, 'readwrite': 1, 'unit': ''}, 
    '8740': {'name': 'Raumtemperatur 1', 'dataType_name': 'TEMP', 'dataType_family': 'VALS', 'destination': '0', 'error': 0, 'value': '24.9', 'desc': '', 'precision': 0.1, 'dataType': 0, 'readonly': 1, 'readwrite': 1, 'unit': '°C'}, 
    '8749': {'name': 'Raumthermostat 1', 'dataType_name': 'ENUM', 'dataType_family': 'ENUM', 'destination': '0', 'error': 7, 'value': '', 'desc': '', 'dataType': 1, 'readonly': 1, 'readwrite': 1, 'unit': ''}}
```

# failing

```
BSBLAN heating_params: ['hvac_mode', 'target_temperature', 'hvac_mode2', 'hvac_action', 'current_temperature', 'room1_thermostat_mode']
BSBLAN data: {
    '700': {'name': 'Betriebsart', 'dataType_name': 'ENUM', 'dataType_family': 'ENUM', 'destination': '0', 'error': 0, 'value': '1', 'desc': 'Automatik', 'dataType': 1, 'readonly': 0, 'readwrite': 0, 'unit': ''}, 
    '710': {'name': 'Komfortsollwert', 'dataType_name': 'TEMP', 'dataType_family': 'VALS', 'destination': '0', 'error': 0, 'value': '23.0', 'desc': '', 'precision': 0.1, 'dataType': 0, 'readonly': 0, 'readwrite': 0, 'unit': '°C'}, 
    '900': {'name': 'Betriebsartumschaltung', 'dataType_name': 'ENUM', 'dataType_family': 'ENUM', 'destination': '0', 'error': 0, 'value': '1', 'desc': 'Schutzbetrieb', 'dataType': 1, 'readonly': 0, 'readwrite': 0, 'unit': ''}, 
    '8000': {'name': 'Status Heizkreis 1', 'dataType_name': 'ENUM', 'dataType_family': 'ENUM', 'destination': '0', 'error': 0, 'value': '114', 'desc': 'Heizbetrieb Komfort', 'dataType': 1, 'readonly': 1, 'readwrite': 1, 'unit': ''}, 
    '8740': {'name': 'Raumtemperatur-Istwert 1', 'dataType_name': 'TEMP', 'dataType_family': 'VALS', 'destination': '0', 'error': 0, 'value': '24.3', 'desc': '', 'precision': 0.1, 'dataType': 0, 'readonly': 1, 'readwrite': 1, 'unit': '°C'}}
2023-11-12 09:06:25.780 ERROR (MainThread) [homeassistant.components.bsblan] Unexpected error fetching bsblan_10.0.0.15 data: zip() argument 2 is shorter than argument 1
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/bsblan/coordinator.py", line 51, in _async_update_data
    return await self.client.state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/bsblan/bsblan.py", line 177, in state
    data = dict(zip(self._heating_params, list(data.values()), strict=True))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: zip() argument 2 is shorter than argument 1
2023-11-12 09:06:25.781 DEBUG (MainThread) [homeassistant.components.bsblan] Finished fetching bsblan_10.0.0.15 data in 1.083 seconds (success: False)
````

Seems like the method is not prepared for missing results.

**Comment by DavidS** [comment]
Since I don't always have access to this device, here's also a dump of all available parameters from it.
[parameter_dump.zip](https://github.com/liudger/python-bsblan/files/13327657/parameter_dump.zip)
